"""Add target_role to PromptTemplate

Revision ID: 0f855fb8593e
Revises: 2d23dcdb32c1
Create Date: 2026-02-28 17:18:30.718313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f855fb8593e'
down_revision: Union[str, None] = '2d23dcdb32c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('target_role', sa.String(length=50), nullable=False, server_default='both'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_templates', 'target_role')
    # ### end Alembic commands ###
