"""Add job description

Revision ID: 2d23dcdb32c1
Revises: 60e7ca4fc516
Create Date: 2026-02-28 17:15:36.839033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d23dcdb32c1'
down_revision: Union[str, None] = '60e7ca4fc516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_description')
    # ### end Alembic commands ###
