"""Add recruiter job info

Revision ID: 60e7ca4fc516
Revises: d9bfd67a016a
Create Date: 2026-02-28 17:00:58.399423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e7ca4fc516'
down_revision: Union[str, None] = 'd9bfd67a016a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
