"""Add image_data to photos

Revision ID: 6bf92cec05ab
Revises: 6fd92913a5e2
Create Date: 2026-02-28 20:56:55.106768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf92cec05ab'
down_revision: Union[str, None] = '6fd92913a5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('photos', sa.Column('content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'content_type')
    op.drop_column('photos', 'image_data')
    # ### end Alembic commands ###
